### PR TITLE
Update ssdp serde

### PR DESCRIPTION
**Pull request by andete**

### CODE REVIEW

**Comment by LFalch** [comment]
AppVeyor failed but it doesn't seem to be because of the code.

**Comment by LFalch** [comment]
Looks good!

**Review by LFalch — APPROVED** [review]

**Comment by LFalch** [comment]
`Bridge::get_all_groups` seems to have broken because of this. I cannot tell why. @andete

**Comment by andete** [comment]
Hmm, maybe serde changed how deserializing into a BTreeMap is done?
My https://github.com/andete/hue_persistence app is still working fine.
Latest hue_persistance uses my latest fork using hyper 0.11/Futures here though to be able to add a timeout to the hue request.
https://github.com/andete/philipshue/tree/hyper_0.11

**Comment by LFalch** [comment]
I seem to have found a fix. Apparently deserialising a list of strings to a `Vec<usize>` doesn't work anymore. So I had to make a function for that.

**Pull request merged**
