### PR TITLE
Add serialization for `Light` structure

### PR DESCRIPTION
**Pull request by matthieugouel**
Hello ! 

First, thanks a lot for you work on this library, it's very useful ! :-) 
Disclaimer, I'm playing with Rust only for a couple of days so I'm a very very beginner. I hope my request is not too silly. 

I'm trying to code a little IHM with Rocket along with your lib. I have trouble to convert the `Light` structure into something compatible with  the`Template::render()` function of Rocket. I noticed that the `Light` structure does not implement  the `Serialize` trait. I just added it and now I can directly use the `Light` structure in the template rendering. 

Maybe there is a reason not to implement it but I'm too new in Rust to understand the side effects.

Best, 
Matthieu.

### CODE REVIEW

**Comment by LFalch** [comment]
Stupid AppVeyor acting up

**Comment by LFalch** [comment]
I think the reason it `Serialize` wasn't implemented was because it wasn't needed in the library. I didn't consider the possible someone might want to serialise it for use outside this library's internals. I'll run a quick test on my computer to make it sure there are no problems on Windows since AppVeyor is acting.

Thanks!

**Review by LFalch — APPROVED** [review]

**Comment by LFalch** [comment]
I can release this with a version bump too if you want it.

**Comment by matthieugouel** [comment]
Hello,

Thanks a lot for the merge ! My first PR in Rust :'-) 
I'm using it for a mini project but it's absolutly not in a rush.

**Pull request merged**
